name: Upload Schema to S3
on:
  workflow_dispatch:
    
jobs:
  upload-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Extract version from branch or tag name
      - name: Extract version
        id: extract_version
        run: |
          # This assumes your version is in the format v0.4.0 in a tag
          # You can modify this to extract from other sources if needed
          VERSION=$(echo ${GITHUB_REF#refs/tags/} | grep -oP 'v\d+\.\d+\.\d+' || echo ${GITHUB_REF#refs/heads/})
          echo "version=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      # Upload the schema file to S3
      - name: Upload schema to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Copy file to S3
        id: upload
        run: |
          # Replace schema.json with your actual schema file path
          aws s3 cp acdc_schema.json s3://${{ secrets.S3_BUCKET }}/cad.json
          echo "s3_key=cad.json" >> $GITHUB_OUTPUT
      
      # Add version tag to the uploaded S3 object
      - name: Tag S3 object with version
        run: |
          aws s3api put-object-tagging \
            --bucket ${{ secrets.S3_BUCKET }} \
            --key ${{ steps.upload.outputs.s3_key }} \
            --tagging '{"TagSet": [{"Key": "version", "Value": "${{ steps.extract_version.outputs.version }}"}]}'
